hw1: add linter
GenesisEducationKyiv/software-engineering-school-4-0-DimaL-cloud pull request #3
Opened 2024-06-09 14:38 UTC by DimaL-cloud

2024-06-11 09:24 UTC, fdemchenko commented
In general code structure is great. Code is readable and easy to understand. One more suggestion is to implement exchange rate caching in future, instead of fetching it each time client make request to your app.

2024-06-11 09:25 UTC, fdemchenko reviewed
In general code structure is great. Code is readable and easy to understand. One more suggestion is to implement exchange rate caching in future, instead of fetching it each time client make request to your app.

2024-06-11 09:25 UTC, fdemchenko commented on pkg/client/exchangerate.go
> +func (e *ExchangeRateClient) GetCurrentExchangeRate() (ExchangeRateResponse, error) {
```GetCurrentExchangeRate```  function supposed to return exchange rate as well as fetch or unmarshal errors, but error is always nil here. In addition, function continues execution after fetch error occurred. Consider returning error instead of logging it.

2024-06-11 09:25 UTC, fdemchenko commented on cmd/main.go
> +	if err := server.Shutdown(context.Background()); err != nil {
From net/http documentation:
"Shutdown works by first closing all open listeners, then closing all idle connections, and then _**waiting indefinitely**_ for connections to return to idle and then shut down."

So, I suggest you to use context.WithTimeout().

2024-06-11 09:25 UTC, fdemchenko commented on cmd/main.go
Overall code structure is fine and readable.

2024-06-11 09:25 UTC, fdemchenko commented on pkg/handler/response.go
What about creating some helper functions for common error status codes?

2024-06-11 09:25 UTC, fdemchenko commented on pkg/models/server.go
What is the purpose of wrapping standard library server into one more type?

2024-06-11 09:25 UTC, fdemchenko commented on pkg/repository/database.go
```NewDB``` does not just create connection pool but also pings database and that's awesome

2024-06-11 09:25 UTC, fdemchenko commented on pkg/repository/subscription.go
> +	return err
Just return ```row.Err()```

2024-06-11 09:25 UTC, fdemchenko commented on pkg/repository/subscription.go
> +	query := fmt.Sprintf("INSERT INTO %s (email) VALUES ($1) ON CONFLICT (email) DO NOTHING", subscriptionsTable)
Consider letting user know email address already exists in database and sending appropriate error code. Extract error from PostgreSQL.

2024-06-11 09:25 UTC, fdemchenko commented on pkg/scheduler/exchangeratenotification.go
> +		exchangerate, err := e.exchangeRateClient.GetCurrentExchangeRate()
Add some retries to increase system reliability. Try to get exchange rate several times, in case previous try was unsuccessful. Some silly network error can leave clients without exchange rate for 24 hours.

2024-06-12 19:27 UTC, MaxDMT16 requested changes
In general code is well-structured 👍 
Left few comments. They are not related to HA task, but would improve the project.
Could you please check Filipp's comments as well

2024-06-12 19:27 UTC, MaxDMT16 commented on cmd/main.go
> +	return viper.ReadInConfig()
Could you please explain the purpose of having 2 config files - .env & config.yml?

It's better to be consistent across the project and use one approach

2024-06-12 19:27 UTC, MaxDMT16 commented on pkg/repository/subscription.go
> +	return err
I'd advice wrapping errors with `fmt.Errorf()`. It will give an ability to provide additional context with returned error

2024-06-12 19:27 UTC, MaxDMT16 commented on pkg/scheduler/exchangeratenotification.go
> +	err := c.AddFunc(viper.GetString("exchange_rate.notification_cron"), func() {
For now, when error occurs we just returning from the func.
How would you know the root cause of the fail in such case?

2024-06-12 19:27 UTC, MaxDMT16 commented on pkg/client/exchangerate.go
> +func (e *ExchangeRateClient) GetCurrentExchangeRate() (ExchangeRateResponse, error) {
The same comment from me on not returning error.
Methods signature misleads and don't return error when its supposed to

2024-06-12 19:30 UTC, MaxDMT16 commented
It was not requested in HA, but could be useful in future - I'd recommend to add linter in [pre-commit hooks](https://pre-commit.com/). It will run check before each commit.

2024-06-13 19:30 UTC, DimaL-cloud commented on cmd/main.go
> +	return viper.ReadInConfig()
config.yml is for general settings and .env is for storing sensitive information like mail credentials. I agree that maybe it is better to use one format and replace files

2024-06-13 19:35 UTC, DimaL-cloud commented on pkg/handler/response.go
There are a lot of codes, so imho, it is easier to use existing one and pass exact code

2024-06-13 19:39 UTC, DimaL-cloud commented on pkg/models/server.go
Extracted server set up in different file

2024-06-13 19:40 UTC, DimaL-cloud commented
Thank you for reviewing code. I agree with almost all points

2024-06-14 17:19 UTC, merged